language: java

services:
  - docker

before_script:
  - ".travis/bintray.sh"

script:
  - docker build -t keeps/dbvtk .

deploy:
  provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    all_branches: true