version: '3.2'
services:
  dbptke:
    image: keeps/dbvtk:staging
    ports:
      - 8080:8080
    environment:
      - SOLR_ZOOKEEPER_HOSTS=solr:9983
      - CAS_ENABLED=false
    volumes:
      # configuration overrides
      - ./config/dbvtk-viewer.properties:/dbvtk/config/dbvtk-viewer.properties:ro
    depends_on:
      - solr
  solr:
    image: solr:8.4
    ports:
      - 8983:8983
    command: -c # Use cloud mode
    
    
