version: "3.2"
services:
  dbptke:
    image: keeps/dbvtk:latest
    networks:
      - zoonet
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - SOLR_ZOOKEEPER_HOSTS=solr:9983
      - CAS_ENABLED=true
      - CAS_INTERNAL_URL=http://cas:8080
      - CAS_EXTERNAL_URL=http://localhost:8181
      - DBVTK_INTERNAL_URL=http://dbptke:8080
      - DBVTK_EXTERNAL_URL=http://localhost:8080
      - DBPTKE_SHARED_FOLDER=/volumes/siards
    volumes:
      # configuration overrides
      - ./dbptke/config/dbvtk-viewer.properties:/dbvtk/config/dbvtk-viewer.properties:ro
      # map /volumes/siards to the desired folder
    depends_on:
      - solr
    entrypoint: java -Djavax.xml.parsers.DocumentBuilderFactory=org.apache.xerces.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.parsers.SAXParserFactory=org.apache.xerces.jaxp.SAXParserFactoryImpl -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -jar /app.war
  solr:
    image: solr:8.4
    networks:
      - zoonet
    ports:
      - 8983:8983
    command: -c # Use cloud mode
  cas:
    image: cas:latest
    build: 
      context: ./image/cas
    networks:
      - zoonet
    ports:
      - 8181:8080
    volumes:
      - ./thekeystore:/etc/cas/thekeystore
      - ./cas/attribute-repository.json:/etc/cas/attribute-repository.json
      - ./cas/users.txt:/etc/cas/config/users.txt
      - ./cas/services:/etc/cas/config/services
      - ./cas/cas.properties:/etc/cas/config/cas.properties

networks:
  zoonet:
