version: '3.2'
services:
  dbvtk:
    image: keeps/dbvtk:latest
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - SOLR_ZOOKEEPER_HOSTS=solr:9983
    #volumes:
      # configuration overrides
      # - ./config/logback.xml:/dbvtk/config/logback.xml:ro
      # - ./config/dbvtk-viewer.properties:/dbvtk/config/dbvtk-viewer.properties:ro
    depends_on:
      - solr
  solr:
    image: solr:7.7
    ports:
      - 8983:8983
    command: -c # Use cloud mode
